# Explicit frozen target inventory. No unsafe target is installed.
if(SAFETY_CASE STREQUAL "C01" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C01_bad safety/qualification/C01/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C01_good safety/qualification/C01/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C02" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C02_bad safety/qualification/C02/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C02_good safety/qualification/C02/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C03" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C03_bad safety/qualification/C03/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C03_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C03_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C03_good safety/qualification/C03/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C03_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C03_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C04" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C04_bad safety/qualification/C04/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C04_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C04_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C04_good safety/qualification/C04/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C04_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C04_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C05" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C05_bad safety/qualification/C05/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C05_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C05_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C05_good safety/qualification/C05/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C05_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C05_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C06" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C06_bad safety/qualification/C06/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C06_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C06_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C06_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C06_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C06_good safety/qualification/C06/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C06_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C06_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C06_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C06_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C07" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C07_bad safety/qualification/C07/bad.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C07_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C07_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C07_good safety/qualification/C07/good.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C07_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C07_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C08" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C08_bad safety/qualification/C08/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C08_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C08_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C08_good safety/qualification/C08/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C08_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C08_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C09" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C09_bad safety/qualification/C09/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C09_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C09_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C09_good safety/qualification/C09/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C09_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C09_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C10" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C10_bad safety/qualification/C10/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C10_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C10_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C10_good safety/qualification/C10/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C10_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C10_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C11" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "msan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C11_bad safety/qualification/C11/bad.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C11_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C11_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C11_good safety/qualification/C11/good.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C11_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C11_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C12" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "msan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C12_bad safety/qualification/C12/bad.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C12_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C12_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C12_good safety/qualification/C12/good.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C12_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C12_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C13" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "ubsan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C13_bad safety/qualification/C13/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C13_good safety/qualification/C13/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C14" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "ubsan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C14_bad safety/qualification/C14/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C14_good safety/qualification/C14/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C15" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "ubsan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C15_bad safety/qualification/C15/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C15_good safety/qualification/C15/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C16" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "ubsan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C16_bad safety/qualification/C16/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C16_good safety/qualification/C16/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C17" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "ubsan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C17_bad safety/qualification/C17/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C17_good safety/qualification/C17/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C18" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "integer")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C18_bad safety/qualification/C18/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C18_good safety/qualification/C18/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C19" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "integer")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C19_bad safety/qualification/C19/bad.c)
    target_compile_options(C19_bad PRIVATE -Wno-error=conversion -Wno-error=sign-conversion)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C19_good safety/qualification/C19/good.c)
    target_compile_options(C19_good PRIVATE -Wno-error=conversion -Wno-error=sign-conversion)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C20" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "integer")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C20_bad safety/qualification/C20/bad.c)
    target_compile_options(C20_bad PRIVATE -Wno-error=conversion -Wno-error=sign-conversion)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C20_good safety/qualification/C20/good.c)
    target_compile_options(C20_good PRIVATE -Wno-error=conversion -Wno-error=sign-conversion)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C21" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "tsan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C21_bad safety/qualification/C21/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C21_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C21_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C21_good safety/qualification/C21/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C21_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C21_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C22" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "gcc-analyzer")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C22_bad safety/qualification/C22/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C22_good safety/qualification/C22/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C23" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "gcc-analyzer")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C23_bad safety/qualification/C23/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C23_good safety/qualification/C23/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C24" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "csa")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C24_bad safety/qualification/C24/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C24_good safety/qualification/C24/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C25" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "tidy")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C25_bad safety/qualification/C25/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C25_good safety/qualification/C25/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C26" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "warnings")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C26_bad safety/qualification/C26/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C26_good safety/qualification/C26/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C27" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "warnings")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C27_bad safety/qualification/C27/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C27_good safety/qualification/C27/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C28" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "ast")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C28_bad safety/qualification/C28/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C28_good safety/qualification/C28/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C29" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "warnings")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C29_bad safety/qualification/C29/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C29_good safety/qualification/C29/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C30" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "asan")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C30_bad safety/qualification/C30/bad.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C30_bad PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C30_bad PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C30_good safety/qualification/C30/good.c safety/qualification/support.c)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(C30_good PRIVATE -Wno-error=return-local-addr -Wno-error=use-after-free -Wno-error=uninitialized -Wno-error=maybe-uninitialized)
    else()
      target_compile_options(C30_good PRIVATE -Wno-error=return-stack-address -Wno-error=uninitialized)
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C31" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "functional")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C31_bad safety/qualification/C31/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C31_good safety/qualification/C31/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C32" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "fuzz")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    if(SAFETY_PROFILE STREQUAL "fuzz")
      safety_add_program(C32_bad ${fuzz_harness} ${fuzz_bad})
      target_link_options(C32_bad PRIVATE -fsanitize=fuzzer)
    else()
      safety_add_program(C32_bad ${fuzz_harness} ${fuzz_bad} ${fuzz_driver})
    endif()
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    if(SAFETY_PROFILE STREQUAL "fuzz")
      safety_add_program(C32_good ${fuzz_harness} ${fuzz_good})
      target_link_options(C32_good PRIVATE -fsanitize=fuzzer)
    else()
      safety_add_program(C32_good ${fuzz_harness} ${fuzz_good} ${fuzz_driver})
    endif()
  endif()
endif()
if(SAFETY_CASE STREQUAL "C33" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "functional")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C33_bad safety/qualification/C33/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C33_good safety/qualification/C33/good.c)
  endif()
endif()
if(SAFETY_CASE STREQUAL "C34" OR (SAFETY_CASE STREQUAL "" AND (SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "functional")))
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "bad")
    safety_add_program(C34_bad safety/qualification/C34/bad.c)
  endif()
  if(SAFETY_VARIANT STREQUAL "both" OR SAFETY_VARIANT STREQUAL "good")
    safety_add_program(C34_good safety/qualification/C34/good.c)
  endif()
endif()
