# Additional discovery for developer feedback only. Existing acceptance jobs
# keep their default CTest inventory and all explicit negative target routes.
option(SC_DEVELOPER_CONTEXT "Register the developer feedback context" OFF)
if(SC_DEVELOPER_CONTEXT)
  option(SC_DEVELOPER_DEMO "Explicit isolated developer qualification workspace" OFF)
  if(SC_DEVELOPER_DEMO)
    if(NOT EXISTS "${SC_DEVELOPER_PRIMARY}")
      message(FATAL_ERROR "Designated isolated candidate input is missing")
    endif()
    set(sc_developer_sources "${SC_DEVELOPER_PRIMARY}" safety/qualification/developer/control.c)
    if(SC_DEVELOPER_EXTRA)
      list(APPEND sc_developer_sources /fixture/extra.c)
    endif()
    configure_file(safety/qualification/developer/generated.h.in developer-generated.h @ONLY)
    safety_add_program(developer_demo ${sc_developer_sources})
    target_include_directories(developer_demo PRIVATE "${PROJECT_SOURCE_DIR}/safety/qualification/developer" "${PROJECT_BINARY_DIR}")
    target_compile_definitions(developer_demo PRIVATE _POSIX_C_SOURCE=200809L SC_DEVELOPER_DEFINE_VALUE=${SC_DEVELOPER_DEFINE_VALUE})
    target_link_libraries(developer_demo PRIVATE sc_foundation pthread)
    set_target_properties(developer_demo PROPERTIES BUILD_RPATH "${SC_DEPENDENCY_PREFIX}/lib")
    add_test(NAME developer.pair COMMAND developer_demo pair)
    set_tests_properties(developer.pair PROPERTIES LABELS "developer;isolated-demo")
  endif()
  foreach(sc_group sizes text bytes lists maps errors cleanup)
    add_test(NAME foundation.${sc_group} COMMAND foundation_contracts ${sc_group})
    set_tests_properties(foundation.${sc_group} PROPERTIES LABELS "foundation;developer")
  endforeach()
  add_test(NAME foundation.retain-accounting COMMAND foundation_contracts retain-accounting)
  add_test(NAME foundation.recipes COMMAND foundation_recipes)
  set_tests_properties(foundation.retain-accounting foundation.recipes
                      PROPERTIES LABELS "foundation;developer")
endif()
