# Exact profile input selection, never ambient pkg-config or global link paths.
if(NOT EXISTS "${PROJECT_SOURCE_DIR}/foundation.lock.json")
  message(FATAL_ERROR "locked foundation inputs are mandatory")
endif()
file(READ "${PROJECT_SOURCE_DIR}/foundation.lock.json" sc_lock)
string(JSON sc_state GET "${sc_lock}" status)
if(NOT sc_state STREQUAL "ARTIFACTS_QUALIFIED")
  message(FATAL_ERROR "foundation dependency artifacts are not qualified")
endif()
if(SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "strict")
  if(CMAKE_C_FLAGS MATCHES "-O2")
    set(sc_optimization O2)
  else()
    set(sc_optimization O0)
  endif()
  if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
    set(SC_DEPENDENCY_PROFILE "gcc-${sc_optimization}")
  else()
    set(SC_DEPENDENCY_PROFILE "clang-${sc_optimization}")
  endif()
elseif(SAFETY_PROFILE STREQUAL "gcc-analyzer")
  set(SC_DEPENDENCY_PROFILE gcc-O0)
elseif(SAFETY_PROFILE STREQUAL "hardened")
  set(SC_DEPENDENCY_PROFILE clang-O2)
elseif(SAFETY_PROFILE STREQUAL "integer")
  # Upstream defined unsigned operations keep UBSan; first-party integer flags
  # remain unchanged. This equivalence is explicit in the protected lock.
  set(SC_DEPENDENCY_PROFILE ubsan)
else()
  set(SC_DEPENDENCY_PROFILE "${SAFETY_PROFILE}")
endif()
set(SC_DEPENDENCY_PREFIX "/opt/foundation/${SC_DEPENDENCY_PROFILE}")
string(JSON sc_count LENGTH "${sc_lock}" profiles "${SC_DEPENDENCY_PROFILE}" files)
math(EXPR sc_last "${sc_count}-1")
foreach(sc_i RANGE ${sc_last})
  string(JSON sc_file MEMBER "${sc_lock}" profiles "${SC_DEPENDENCY_PROFILE}" files ${sc_i})
  string(JSON sc_expected GET "${sc_lock}" profiles "${SC_DEPENDENCY_PROFILE}" files "${sc_file}")
  if(NOT EXISTS "${SC_DEPENDENCY_PREFIX}/${sc_file}")
    message(FATAL_ERROR "locked dependency file missing: ${sc_file}")
  endif()
  file(SHA256 "${SC_DEPENDENCY_PREFIX}/${sc_file}" sc_actual)
  if(NOT sc_actual STREQUAL sc_expected)
    message(FATAL_ERROR "locked dependency file substituted: ${sc_file}")
  endif()
endforeach()
add_library(ScGLib SHARED IMPORTED GLOBAL)
set_target_properties(ScGLib PROPERTIES
  IMPORTED_LOCATION "${SC_DEPENDENCY_PREFIX}/lib/libglib-2.0.so"
  IMPORTED_SONAME libglib-2.0.so.0
  INTERFACE_INCLUDE_DIRECTORIES "${SC_DEPENDENCY_PREFIX}/include/glib-2.0;${SC_DEPENDENCY_PREFIX}/lib/glib-2.0/include"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${SC_DEPENDENCY_PREFIX}/include/glib-2.0;${SC_DEPENDENCY_PREFIX}/lib/glib-2.0/include"
  INTERFACE_COMPILE_DEFINITIONS "GLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_70;GLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_70")
add_library(Sc::GLib ALIAS ScGLib)
add_library(sc_foundation STATIC foundation/src/sc-foundation.c)
safety_target(sc_foundation)
target_include_directories(sc_foundation PUBLIC "${PROJECT_SOURCE_DIR}/foundation/include")
target_link_libraries(sc_foundation PUBLIC Sc::GLib)
set(FOUNDATION_DISABLED_GUARDS "" CACHE STRING "Explicit qualification of first-party guard macros")
foreach(sc_definition IN LISTS FOUNDATION_DISABLED_GUARDS)
  if(NOT sc_definition MATCHES "^(NDEBUG|G_DISABLE_ASSERT|G_DISABLE_CHECKS)$")
    message(FATAL_ERROR "unapproved foundation macro variant")
  endif()
  target_compile_definitions(sc_foundation PRIVATE "${sc_definition}")
endforeach()
safety_add_program(foundation_contracts foundation/tests/contracts.c foundation/tests/dependency-identity.c)
target_link_libraries(foundation_contracts PRIVATE sc_foundation dl)
target_include_directories(foundation_contracts PRIVATE "${PROJECT_SOURCE_DIR}/foundation/tests")
target_compile_definitions(foundation_contracts PRIVATE ${FOUNDATION_DISABLED_GUARDS})
set_target_properties(foundation_contracts PROPERTIES BUILD_RPATH "${SC_DEPENDENCY_PREFIX}/lib")
# Existing CTest accounting stays intact. Foundation discovery/counting belongs
# to its additional mandatory inventory rather than recursive aggregate calls.
