# Exact profile input selection, never ambient pkg-config or global link paths.
if(NOT EXISTS "${PROJECT_SOURCE_DIR}/foundation.lock.json")
  message(FATAL_ERROR "locked foundation inputs are mandatory")
endif()
file(READ "${PROJECT_SOURCE_DIR}/foundation.lock.json" sc_lock)
string(JSON sc_state GET "${sc_lock}" status)
if(NOT sc_state STREQUAL "ARTIFACTS_QUALIFIED")
  message(FATAL_ERROR "foundation dependency artifacts are not qualified")
endif()
if(SAFETY_PROFILE STREQUAL "ordinary" OR SAFETY_PROFILE STREQUAL "strict" OR SAFETY_PROFILE STREQUAL "warnings")
  if(CMAKE_C_FLAGS MATCHES "-O2")
    set(sc_optimization O2)
  else()
    set(sc_optimization O0)
  endif()
  if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
    set(SC_DEPENDENCY_PROFILE "gcc-${sc_optimization}")
  else()
    set(SC_DEPENDENCY_PROFILE "clang-${sc_optimization}")
  endif()
elseif(SAFETY_PROFILE STREQUAL "gcc-analyzer")
  set(SC_DEPENDENCY_PROFILE gcc-O0)
elseif(SAFETY_PROFILE STREQUAL "hardened")
  set(SC_DEPENDENCY_PROFILE clang-O2)
elseif(SAFETY_PROFILE STREQUAL "integer")
  # Upstream defined unsigned operations keep UBSan; first-party integer flags
  # remain unchanged. This equivalence is explicit in the protected lock.
  set(SC_DEPENDENCY_PROFILE ubsan)
else()
  set(SC_DEPENDENCY_PROFILE "${SAFETY_PROFILE}")
endif()
set(SC_DEPENDENCY_PREFIX "/opt/foundation/${SC_DEPENDENCY_PROFILE}")
string(JSON sc_count LENGTH "${sc_lock}" profiles "${SC_DEPENDENCY_PROFILE}" files)
math(EXPR sc_last "${sc_count}-1")
foreach(sc_i RANGE ${sc_last})
  string(JSON sc_file MEMBER "${sc_lock}" profiles "${SC_DEPENDENCY_PROFILE}" files ${sc_i})
  string(JSON sc_expected GET "${sc_lock}" profiles "${SC_DEPENDENCY_PROFILE}" files "${sc_file}")
  if(NOT EXISTS "${SC_DEPENDENCY_PREFIX}/${sc_file}")
    message(FATAL_ERROR "locked dependency file missing: ${sc_file}")
  endif()
  file(SHA256 "${SC_DEPENDENCY_PREFIX}/${sc_file}" sc_actual)
  if(NOT sc_actual STREQUAL sc_expected)
    message(FATAL_ERROR "locked dependency file substituted: ${sc_file}")
  endif()
endforeach()
add_library(ScGLib SHARED IMPORTED GLOBAL)
set_target_properties(ScGLib PROPERTIES
  IMPORTED_LOCATION "${SC_DEPENDENCY_PREFIX}/lib/libglib-2.0.so"
  IMPORTED_SONAME libglib-2.0.so.0
  INTERFACE_INCLUDE_DIRECTORIES "${SC_DEPENDENCY_PREFIX}/include/glib-2.0;${SC_DEPENDENCY_PREFIX}/lib/glib-2.0/include"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${SC_DEPENDENCY_PREFIX}/include/glib-2.0;${SC_DEPENDENCY_PREFIX}/lib/glib-2.0/include"
  INTERFACE_COMPILE_DEFINITIONS "GLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_70;GLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_70")
add_library(Sc::GLib ALIAS ScGLib)
set(FOUNDATION_MUTANT "NONE" CACHE STRING "Protected test-only foundation mutation")
set(sc_foundation_source "${PROJECT_SOURCE_DIR}/foundation/src/sc-foundation.c")
if(NOT FOUNDATION_MUTANT STREQUAL "NONE")
  file(READ "${PROJECT_SOURCE_DIR}/safety/foundation-mutants.json" sc_mutants)
  string(JSON sc_mutant_case ERROR_VARIABLE sc_mutant_error GET "${sc_mutants}" mutants "${FOUNDATION_MUTANT}" case_id)
  if(sc_mutant_error)
    message(FATAL_ERROR "uninventoried foundation mutation")
  endif()
  string(JSON sc_mutant_recipe GET "${sc_mutants}" recipe)
  string(JSON sc_mutant_expected GET "${sc_mutants}" recipe_sha256)
  file(SHA256 "${PROJECT_SOURCE_DIR}/${sc_mutant_recipe}" sc_mutant_actual)
  if(NOT sc_mutant_actual STREQUAL sc_mutant_expected)
    message(FATAL_ERROR "foundation mutation recipe changed")
  endif()
  execute_process(COMMAND python3 "${PROJECT_SOURCE_DIR}/${sc_mutant_recipe}" "${FOUNDATION_MUTANT}" "${CMAKE_BINARY_DIR}/foundation-mutation"
    RESULT_VARIABLE sc_generated OUTPUT_FILE "${CMAKE_BINARY_DIR}/mutation-generation.log" ERROR_FILE "${CMAKE_BINARY_DIR}/mutation-generation-errors.log" TIMEOUT 10)
  if(NOT sc_generated EQUAL 0)
    message(FATAL_ERROR "foundation mutation generation blocked")
  endif()
  set(sc_foundation_source "${CMAKE_BINARY_DIR}/foundation-mutation/sc-foundation-mutant.c")
endif()
add_library(sc_foundation STATIC "${sc_foundation_source}")
safety_target(sc_foundation)
target_include_directories(sc_foundation PUBLIC "${PROJECT_SOURCE_DIR}/foundation/include")
target_link_libraries(sc_foundation PUBLIC Sc::GLib)
set(FOUNDATION_DISABLED_GUARDS "" CACHE STRING "Explicit qualification of first-party guard macros")
foreach(sc_definition IN LISTS FOUNDATION_DISABLED_GUARDS)
  if(NOT sc_definition MATCHES "^(NDEBUG|G_DISABLE_ASSERT|G_DISABLE_CHECKS)$")
    message(FATAL_ERROR "unapproved foundation macro variant")
  endif()
  target_compile_definitions(sc_foundation PRIVATE "${sc_definition}")
endforeach()
safety_add_program(foundation_contracts foundation/tests/contracts.c foundation/tests/dependency-identity.c)
target_link_libraries(foundation_contracts PRIVATE sc_foundation dl)
target_include_directories(foundation_contracts PRIVATE "${PROJECT_SOURCE_DIR}/foundation/tests")
target_compile_definitions(foundation_contracts PRIVATE ${FOUNDATION_DISABLED_GUARDS})
set_target_properties(foundation_contracts PROPERTIES BUILD_RPATH "${SC_DEPENDENCY_PREFIX}/lib")
safety_add_program(foundation_recipes foundation/tests/recipes.c foundation/tests/dependency-identity.c)
target_link_libraries(foundation_recipes PRIVATE sc_foundation dl)
target_include_directories(foundation_recipes PRIVATE "${PROJECT_SOURCE_DIR}/foundation/tests")
set_target_properties(foundation_recipes PROPERTIES BUILD_RPATH "${SC_DEPENDENCY_PREFIX}/lib")
# Existing CTest accounting stays intact. Foundation discovery/counting belongs
# to its additional mandatory inventory rather than recursive aggregate calls.

if(SAFETY_PROFILE STREQUAL "fuzz")
  safety_add_program(foundation_fuzzer foundation/tests/stateful-fuzzer.c foundation/tests/dependency-identity.c)
  target_link_libraries(foundation_fuzzer PRIVATE sc_foundation dl)
  target_include_directories(foundation_fuzzer PRIVATE "${PROJECT_SOURCE_DIR}/foundation/tests")
  target_link_options(foundation_fuzzer PRIVATE -fsanitize=fuzzer)
  set_target_properties(foundation_fuzzer PROPERTIES BUILD_RPATH "${SC_DEPENDENCY_PREFIX}/lib")
endif()

set(FOUNDATION_CASE "NONE" CACHE STRING "Explicit inventoried foundation qualification case")
if(NOT FOUNDATION_CASE STREQUAL "NONE")
  if(NOT FOUNDATION_CASE MATCHES "^F(01|02|03|14|17|18|19)$")
    message(FATAL_ERROR "foundation runtime case is not inventoried")
  endif()
  file(READ "${PROJECT_SOURCE_DIR}/safety/foundation-fixtures.json" sc_fixtures)
  string(JSON sc_case_count LENGTH "${sc_fixtures}" cases)
  math(EXPR sc_case_last "${sc_case_count}-1")
  set(sc_case_source "")
  foreach(sc_case_i RANGE ${sc_case_last})
    string(JSON sc_id GET "${sc_fixtures}" cases ${sc_case_i} id)
    if(sc_id STREQUAL FOUNDATION_CASE)
      string(JSON sc_case_source GET "${sc_fixtures}" cases ${sc_case_i} runtime_source)
      string(JSON sc_case_hash GET "${sc_fixtures}" cases ${sc_case_i} source_sha256)
    endif()
  endforeach()
  if(NOT sc_case_source MATCHES "^safety/qualification/foundation/F[0-9][0-9]\\.c$")
    message(FATAL_ERROR "foundation fixture source missing")
  endif()
  file(SHA256 "${PROJECT_SOURCE_DIR}/${sc_case_source}" sc_fixture_actual)
  if(NOT sc_fixture_actual STREQUAL sc_case_hash)
    message(FATAL_ERROR "foundation fixture source changed")
  endif()
  if(FOUNDATION_CASE STREQUAL "F19")
    if(NOT SAFETY_PROFILE STREQUAL "ordinary")
      message(FATAL_ERROR "GLib fail-stop injection is ordinary unsanitized static test linkage only")
    endif()
    add_library(ScGLibStatic STATIC IMPORTED)
    set_target_properties(ScGLibStatic PROPERTIES
      IMPORTED_LOCATION "${SC_DEPENDENCY_PREFIX}/lib/libglib-2.0.a"
      INTERFACE_INCLUDE_DIRECTORIES "${SC_DEPENDENCY_PREFIX}/include/glib-2.0;${SC_DEPENDENCY_PREFIX}/lib/glib-2.0/include")
    safety_add_program(F19_backend "${sc_case_source}")
    target_link_libraries(F19_backend PRIVATE ScGLibStatic m dl)
    target_link_options(F19_backend PRIVATE -Wl,--wrap=malloc)
  else()
  foreach(sc_variant bad good)
    safety_add_program(${FOUNDATION_CASE}_${sc_variant} "${sc_case_source}" foundation/tests/dependency-identity.c)
    target_link_libraries(${FOUNDATION_CASE}_${sc_variant} PRIVATE sc_foundation dl)
    target_include_directories(${FOUNDATION_CASE}_${sc_variant} PRIVATE "${PROJECT_SOURCE_DIR}/foundation/tests")
    if(sc_variant STREQUAL "bad")
      target_compile_definitions(${FOUNDATION_CASE}_${sc_variant} PRIVATE FOUNDATION_NEGATIVE=1)
    else()
      target_compile_definitions(${FOUNDATION_CASE}_${sc_variant} PRIVATE FOUNDATION_NEGATIVE=0)
    endif()
    set_target_properties(${FOUNDATION_CASE}_${sc_variant} PROPERTIES BUILD_RPATH "${SC_DEPENDENCY_PREFIX}/lib")
  endforeach()
  endif()
endif()
