# Project mode: turns <project_dir>/project.json into targets. Every target is
# created through safety_target/safety_add_program, so a project can never
# supply or change compiler, linker or sanitizer settings. Every JSON value is
# validated before use and expanded only inside quotes.
function(_project_name out value pattern)
  string(LENGTH "${value}" length)
  if(length GREATER 63 OR NOT value MATCHES "${pattern}")
    message(FATAL_ERROR "invalid project name: ${value}")
  endif()
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

# Optional array of strings; ARGN is the JSON key path. A missing key is empty,
# a present value of another type is an error.
function(_project_json_list out json)
  string(JSON kind ERROR_VARIABLE err TYPE "${json}" ${ARGN})
  set(items "")
  if(NOT err)
    if(NOT kind STREQUAL "ARRAY")
      message(FATAL_ERROR "project.json key ${ARGN} must be an array")
    endif()
    string(JSON count LENGTH "${json}" ${ARGN})
    if(count GREATER 0)
      math(EXPR last "${count} - 1")
      foreach(i RANGE ${last})
        string(JSON item_kind TYPE "${json}" ${ARGN} ${i})
        if(NOT item_kind STREQUAL "STRING")
          message(FATAL_ERROR "project.json key ${ARGN} must hold only strings")
        endif()
        string(JSON item GET "${json}" ${ARGN} ${i})
        list(APPEND items "${item}")
      endforeach()
    endif()
  endif()
  set(${out} "${items}" PARENT_SCOPE)
endfunction()

function(_project_path out dir relative)
  if(NOT relative MATCHES "^[A-Za-z0-9_+-][A-Za-z0-9_./+-]*$" OR relative MATCHES "(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "project path must be a plain relative path inside the project: ${relative}")
  endif()
  set(${out} "${dir}/${relative}" PARENT_SCOPE)
endfunction()

function(safety_project project_dir)
  # Function scope: safety_target omits the framework include directories for these targets.
  set(_SAFETY_PROJECT_TARGETS ON)
  # A project test FAILs when its output holds a sanitizer or libFuzzer report banner,
  # whatever its exit status. The banners come from the framework policy (one list,
  # also read by tools/project_check.py); each is literal text, safe as a regex.
  file(READ "${PROJECT_SOURCE_DIR}/safety/project-policy.json" policy_json)
  _project_json_list(sanitizer_banners "${policy_json}" sanitizer_banners)
  if(NOT sanitizer_banners)
    message(FATAL_ERROR "safety/project-policy.json lists no sanitizer_banners")
  endif()
  foreach(banner IN LISTS sanitizer_banners)
    if(NOT banner MATCHES "^[A-Za-z][A-Za-z :-]*$")
      message(FATAL_ERROR "sanitizer banner is not literal text: ${banner}")
    endif()
  endforeach()
  get_filename_component(project_dir "${project_dir}" ABSOLUTE)
  set(manifest "${project_dir}/project.json")
  if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "project.json not found in ${project_dir}")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
  file(READ "${manifest}" json)
  string(JSON schema GET "${json}" schema_version)
  if(NOT schema STREQUAL "1")
    message(FATAL_ERROR "unsupported project schema_version: ${schema}")
  endif()
  set(module_pattern "^[a-z][a-z0-9_]*$")
  set(program_pattern "^[a-z][a-z0-9_-]*$")
  string(JSON module_count LENGTH "${json}" modules)
  if(module_count GREATER 0)
    math(EXPR last_module "${module_count} - 1")
    foreach(m RANGE ${last_module})
      string(JSON module GET "${json}" modules ${m})
      string(JSON raw_name GET "${module}" name)
      _project_name(module_name "${raw_name}" "${module_pattern}")
      _project_json_list(source_names "${module}" sources)
      set(sources "")
      foreach(source IN LISTS source_names)
        _project_path(full "${project_dir}" "${source}")
        list(APPEND sources "${full}")
      endforeach()
      if(NOT sources)
        message(FATAL_ERROR "module ${module_name} has no sources")
      endif()
      set(library "project_${module_name}")
      add_library("${library}" STATIC ${sources})
      safety_target("${library}")
      target_include_directories("${library}" PUBLIC "${project_dir}/include")
      _project_json_list(test_names "${module}" tests)
      foreach(test IN LISTS test_names)
        _project_path(test_source "${project_dir}" "${test}")
        get_filename_component(base "${test}" NAME_WE)
        _project_name(base "${base}" "^[A-Za-z0-9_-]+$")
        set(test_target "project_test_${module_name}_${base}")
        safety_add_program("${test_target}" "${test_source}")
        target_link_libraries("${test_target}" PRIVATE "${library}")
        add_test(NAME "project.${module_name}.${base}" COMMAND "${test_target}")
        set_tests_properties("project.${module_name}.${base}" PROPERTIES LABELS unit
          FAIL_REGULAR_EXPRESSION "${sanitizer_banners}")
      endforeach()
    endforeach()
  endif()
  string(JSON run_kind ERROR_VARIABLE run_err TYPE "${json}" run)
  set(run_program "")
  set(run_args "")
  if(NOT run_err)
    if(NOT run_kind STREQUAL "OBJECT")
      message(FATAL_ERROR "project.json key run must be an object")
    endif()
    string(JSON raw_run GET "${json}" run program)
    _project_name(run_program "${raw_run}" "${program_pattern}")
    _project_json_list(run_args "${json}" run args)
    foreach(arg IN LISTS run_args)
      if(arg MATCHES "\\$<" OR arg MATCHES "[\r\n]")
        message(FATAL_ERROR "run.args item is not allowed: ${arg}")
      endif()
    endforeach()
    # ';' cannot appear: it would already have split the item, so reject it in the raw text.
    string(JSON args_count ERROR_VARIABLE args_err LENGTH "${json}" run args)
    if(NOT args_err AND args_count GREATER 0)
      math(EXPR last_arg "${args_count} - 1")
      foreach(a RANGE ${last_arg})
        string(JSON raw_arg GET "${json}" run args ${a})
        string(FIND "${raw_arg}" ";" semicolon)
        if(NOT semicolon EQUAL -1)
          message(FATAL_ERROR "run.args item must not contain ';'")
        endif()
      endforeach()
    endif()
  endif()
  string(JSON program_count LENGTH "${json}" programs)
  if(program_count GREATER 0)
    math(EXPR last_program "${program_count} - 1")
    foreach(p RANGE ${last_program})
      string(JSON program GET "${json}" programs ${p})
      string(JSON raw_program GET "${program}" name)
      _project_name(program_name "${raw_program}" "${program_pattern}")
      string(JSON main GET "${program}" main)
      _project_path(main_source "${project_dir}" "${main}")
      safety_add_program("${program_name}" "${main_source}")
      _project_json_list(program_modules "${program}" modules)
      foreach(raw_module IN LISTS program_modules)
        _project_name(module "${raw_module}" "${module_pattern}")
        if(NOT TARGET "project_${module}")
          message(FATAL_ERROR "program ${program_name} uses unknown module ${module}")
        endif()
        target_link_libraries("${program_name}" PRIVATE "project_${module}")
      endforeach()
      if(program_name STREQUAL run_program)
        add_test(NAME "project.run.${program_name}" COMMAND "${program_name}" ${run_args})
        set_tests_properties("project.run.${program_name}" PROPERTIES LABELS integration
          FAIL_REGULAR_EXPRESSION "${sanitizer_banners}")
      endif()
    endforeach()
  endif()
endfunction()
