# Project mode: turns <project_dir>/project.json into targets. Every target is
# created through safety_target/safety_add_program, so a project can never
# supply or change compiler, linker or sanitizer settings.
function(_project_json_list out json path)
  string(JSON count ERROR_VARIABLE err LENGTH "${json}" ${path})
  set(items "")
  if(NOT err AND count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(i RANGE ${last})
      string(JSON item GET "${json}" ${path} ${i})
      list(APPEND items "${item}")
    endforeach()
  endif()
  set(${out} "${items}" PARENT_SCOPE)
endfunction()

function(_project_path out dir relative)
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "project path must be relative and stay inside the project: ${relative}")
  endif()
  set(${out} "${dir}/${relative}" PARENT_SCOPE)
endfunction()

function(safety_project project_dir)
  get_filename_component(project_dir "${project_dir}" ABSOLUTE)
  set(manifest "${project_dir}/project.json")
  if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "project.json not found in ${project_dir}")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
  file(READ "${manifest}" json)
  string(JSON schema GET "${json}" schema_version)
  if(NOT schema STREQUAL "1")
    message(FATAL_ERROR "unsupported project schema_version: ${schema}")
  endif()
  string(JSON module_count LENGTH "${json}" modules)
  if(module_count GREATER 0)
    math(EXPR last_module "${module_count} - 1")
    foreach(m RANGE ${last_module})
      string(JSON module GET "${json}" modules ${m})
      string(JSON module_name GET "${module}" name)
      _project_json_list(source_names "${module}" sources)
      set(sources "")
      foreach(source IN LISTS source_names)
        _project_path(full "${project_dir}" "${source}")
        list(APPEND sources "${full}")
      endforeach()
      if(NOT sources)
        message(FATAL_ERROR "module ${module_name} has no sources")
      endif()
      set(library project_${module_name})
      add_library(${library} STATIC ${sources})
      safety_target(${library})
      target_include_directories(${library} PUBLIC "${project_dir}/include")
      _project_json_list(test_names "${module}" tests)
      foreach(test IN LISTS test_names)
        _project_path(test_source "${project_dir}" "${test}")
        get_filename_component(base "${test}" NAME_WE)
        set(test_target project_test_${module_name}_${base})
        safety_add_program(${test_target} "${test_source}")
        target_link_libraries(${test_target} PRIVATE ${library})
        add_test(NAME project.${module_name}.${base} COMMAND ${test_target})
        set_tests_properties(project.${module_name}.${base} PROPERTIES LABELS unit)
      endforeach()
    endforeach()
  endif()
  string(JSON run_program ERROR_VARIABLE run_err GET "${json}" run program)
  if(run_err)
    set(run_program "")
  endif()
  _project_json_list(run_args "${json}" run args)
  string(JSON program_count LENGTH "${json}" programs)
  if(program_count GREATER 0)
    math(EXPR last_program "${program_count} - 1")
    foreach(p RANGE ${last_program})
      string(JSON program GET "${json}" programs ${p})
      string(JSON program_name GET "${program}" name)
      string(JSON main GET "${program}" main)
      _project_path(main_source "${project_dir}" "${main}")
      safety_add_program(${program_name} "${main_source}")
      _project_json_list(program_modules "${program}" modules)
      foreach(module IN LISTS program_modules)
        target_link_libraries(${program_name} PRIVATE project_${module})
      endforeach()
      if(program_name STREQUAL run_program)
        add_test(NAME project.run.${program_name} COMMAND ${program_name} ${run_args})
        set_tests_properties(project.run.${program_name} PROPERTIES LABELS integration)
      endif()
    endforeach()
  endif()
endfunction()
