# Target-scoped C17 policy shared by qualification and future application targets.
function(safety_target target)
  set_target_properties(${target} PROPERTIES C_STANDARD 17 C_STANDARD_REQUIRED YES C_EXTENSIONS NO)
  # Project targets (cmake/Project.cmake) see only their own include/ directory: the
  # framework qualification and fuzz directories would let an angle include reach
  # files the project policy does not scan.
  if(NOT _SAFETY_PROJECT_TARGETS)
    target_include_directories(${target} PRIVATE ${PROJECT_SOURCE_DIR}/safety/qualification ${PROJECT_SOURCE_DIR}/fuzz)
  endif()
  if(NOT SAFETY_PROFILE STREQUAL "ordinary")
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror
      -Wconversion -Wsign-conversion -Wshadow -Wformat=2 -Wformat-security
      -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wvla -Wcast-qual
      -Wwrite-strings -Werror=implicit-function-declaration -Werror=incompatible-pointer-types)
  endif()
  if(SAFETY_PROFILE MATCHES "^(asan|ubsan|integer|msan|tsan|fuzz)$")
    target_compile_options(${target} PRIVATE -O1 -g -fno-omit-frame-pointer -fno-optimize-sibling-calls)
    if(SAFETY_PROFILE STREQUAL "asan")
      set(flags -fsanitize=address,undefined -fsanitize-address-use-after-scope -fsanitize-address-use-after-return=always -fno-sanitize-recover=all)
    elseif(SAFETY_PROFILE STREQUAL "ubsan")
      set(flags -fsanitize=undefined -fno-sanitize-recover=all)
    elseif(SAFETY_PROFILE STREQUAL "integer")
      set(flags -fsanitize=undefined,unsigned-integer-overflow,implicit-integer-conversion -fno-sanitize-recover=all)
    elseif(SAFETY_PROFILE STREQUAL "msan")
      set(flags -fsanitize=memory -fsanitize-memory-track-origins=2 -fPIE)
      target_link_options(${target} PRIVATE -pie)
    elseif(SAFETY_PROFILE STREQUAL "tsan")
      set(flags -fsanitize=thread -fPIE)
      target_link_options(${target} PRIVATE -pie)
    else()
      set(flags -fsanitize=address,undefined,fuzzer-no-link -fno-sanitize-recover=all)
    endif()
    target_compile_options(${target} PRIVATE ${flags})
    target_link_options(${target} PRIVATE ${flags})
  elseif(SAFETY_PROFILE STREQUAL "coverage")
    target_compile_options(${target} PRIVATE -O0 -g -fprofile-instr-generate -fcoverage-mapping)
    target_link_options(${target} PRIVATE -fprofile-instr-generate -fcoverage-mapping)
  elseif(SAFETY_PROFILE STREQUAL "hardened")
    target_compile_options(${target} PRIVATE -O2 -g -fstack-protector-strong -fstack-clash-protection -D_FORTIFY_SOURCE=3 -fPIE)
    target_link_options(${target} PRIVATE -pie -Wl,-z,relro,-z,now,-z,noexecstack)
  elseif(SAFETY_PROFILE STREQUAL "gcc-analyzer")
    target_compile_options(${target} PRIVATE -O0 -fanalyzer -Wanalyzer-too-complex -Wanalyzer-symbol-too-complex)
  else()
    target_compile_options(${target} PRIVATE -g)
  endif()
endfunction()
function(safety_add_program target)
  add_executable(${target} ${ARGN})
  safety_target(${target})
  target_link_libraries(${target} PRIVATE pthread)
endfunction()
